name: cpp-linter

on: pull_request

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on
      - uses: cpp-linter/cpp-linter-action@v2.7.5
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: ''
          lines-changed-only: diff
          database: build
          # The following value will only update a single comment
          # in a pull request's thread. Set it to false to disable the comment.
          # Set it to true to post a new comment (and delete the old comment).
          thread-comments: update

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
        #echo "Some files failed the linting checks!"
        #for actual deployment
        # run: exit 1
